#!/usr/bin/env python
print("Content-type:text/html\r\n\r\n")
print("<html>")
print("<head>")
print("")
print("</head>")
print("<body>")
print("<h2>Hello World! This is my first CGI program</h2>")
print("</body>")
print("</html>")
